# this is only for search engines, it does not appear in the home
# as long as the json variables name and description are provided
title: Yifei Gao's Personal Website
description:  Here is some snapshots of my life
baseurl: "https://fahygao.github.io/"
url: https://fahygao.github.io/

# this information is shown on the homepage, all fields are optional and
# can be declared either as a single string or as a string array/hash
json:
  name: Yifei Gao
  chinese: 高一斐
  pronunciation: E-fay-Gaw
  english: Fahy
  description:
    - Hello!
    - Welcome!
    - I love a lot of things...
    - Math, nature, music
    - People, Rollerskating,
    - AI, Elon Musk, Ella❤️
    - Life is beautiful
    - so are you.
  cv: assets/cv.pdf
  # contact:
  #   phone: +1 929 248 7284
  #   email: fahygao@gmail.com
  profiles:
    instagram: https://www.instagram.com/fahygaoyf
    linkedin: https://www.linkedin.com/in/fahy-gao/
    leetcode: https://leetcode.com/Fahygaoyf/
    github: https://github.com/fahygao
    spotify: https://open.spotify.com/user/22wt44me6e7nlz6llzeuf2hji?si=07d0339588984b30
    # bilibili: https://space.bilibili.com/17897244
    my startup - citang: https://linktr.ee/citangge
  jobs: 
    Ice Cream Scooper: 2016 Summer
    Editor-in-chief: 2020 - 2021
    Teacher Assistant: 2019 Summer
    Video Editor: 2019 - 2021
    Vlogger: 2018 - now
    Entreprenuer: 2021 - now
    Band Vocal: 2015 - 2017
    Product Manager: 2021 - now
    Song Writer: 2013 - now
    Quant: 2022 - now







exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never
